INSERT INTO USER (user_name, password) VALUES ("arun", "arun");

INSERT INTO SHAREKEYWORDS (key_words) VALUES ("EPS");
INSERT INTO SHAREKEYWORDS (key_words) VALUES ("Face Value");
INSERT INTO SHAREKEYWORDS (key_words) VALUES ("Market Cap");
INSERT INTO SHAREKEYWORDS (key_words) VALUES ("Maggi");
INSERT INTO SHAREKEYWORDS (key_words) VALUES ("Map");
INSERT INTO SHAREKEYWORDS (key_words) VALUES ("Price");
INSERT INTO SHAREKEYWORDS (key_words) VALUES (">");
INSERT INTO SHAREKEYWORDS (key_words) VALUES ("<");
INSERT INTO SHAREKEYWORDS (key_words) VALUES ("=");
INSERT INTO SHAREKEYWORDS (key_words) VALUES ("<=");
INSERT INTO SHAREKEYWORDS (key_words) VALUES (">=");
INSERT INTO SHAREKEYWORDS (key_words) VALUES ("AND");
INSERT INTO SHAREKEYWORDS (key_words) VALUES ("OR");